run:
  timeout: 5m
  build-tags:
    - integration

linters-settings:
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: changeme
  mnd:
    checks:
      - argument
      - case
      - condition
      - return
    ignored-numbers:
      - '0'
      - '1'
      - '2'
      - '3'
  govet:
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  lll:
    line-length: 300  # Increase line length limit for PowerShell commands
  misspell:
    locale: US

linters:
  enable:
    - bodyclose
    - dupl
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - predeclared  # Check for shadowing of predeclared identifiers

issues:
  exclude-files:
    - ".*\\.pb\\.go$"
  exclude-dirs:
    - frontend/bindings
    - vendor
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - gocritic
        - gocyclo
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    - text: "pattern.*no matching files found"
      linters:
        - typecheck
    # Comprehensive Wails v3 internal package exclusions
    - text: "could not load export data.*wails.*internal"
      linters:
        - typecheck
    - text: "no export data for.*wails.*internal"
      linters:
        - typecheck
    - text: "buildir: failed to load package.*webview.*could not load export data"
      linters:
        - typecheck
    - text: "failed to load package.*webview"
      linters:
        - typecheck
    # Ignore subprocess launch warnings for command execution
    - text: "G204.*Subprocess launched with.*tainted input"
      linters:
        - gosec
    # Ignore long PowerShell command lines for file dialogs
    - path: cmdservice\.go
      text: "line is.*characters long"
      linters:
        - lll
    # Ignore struct field naming for system stats (external API compatibility)
    - path: sysutils\.go
      text: "struct field.*should be.*Percent"
      linters:
        - stylecheck
    # Ignore duplicate embed imports (required for Wails)
    - path: main\.go
      text: "(package.*embed.*imported more than once|other import of.*embed)"
      linters:
        - stylecheck
    # Ignore leading newlines in main function
    - path: main\.go
      text: "unnecessary leading newline"
      linters:
        - whitespace
  max-issues-per-linter: 0
  max-same-issues: 0
