// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function Run(cmd: string): $CancellablePromise<string> {
    return $Call.ByID(1337219506, cmd);
}

/**
 * SelectFile opens a file selection dialog
 */
export function SelectFile(): $CancellablePromise<string> {
    return $Call.ByID(41197827);
}

/**
 * SelectFolder opens a folder selection dialog and looks for lk command
 */
export function SelectFolder(): $CancellablePromise<string> {
    return $Call.ByID(982415261);
}
