// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as CmdService from "./cmdservice.js";
import * as GreetService from "./greetservice.js";
export {
    CmdService,
    GreetService
};
